version: '3'

services:
  db:
    build:
      dockerfile: ./docker/database.dockerfile
      context: .
    image: contact/mysql-database
    container_name: mysql-database
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_pw_shh
      MYSQL_DATABASE: minicursophp_contatos
      MYSQL_USER: minicursophp
      MYSQL_PASSWORD: minicursophp
    ports:
      - "3306:3306"
  web:
    build:
      dockerfile: ./docker/web.dockerfile
      context: .
    image: contact/php-web
    container_name: php-web
    depends_on:
      - db
    volumes:
      - ./src/:/var/www/html/
    ports:
      - "8100:80"
    stdin_open: true
    tty: true
